# Generated by Django 5.1 on 2024-08-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaluser',
            name='role',
            field=models.CharField(choices=[('CREATOR', 'Créateur'), ('SUBSCRIBER', 'Abonné')], default='CREATOR', max_length=30, verbose_name='Rôle'),
        ),
    ]
